IMDB:
  AUTH: cookies
  EMAIL: user@domain.com
  PASSWORD: password123
  COOKIEATMAIN: Atza|IwEBIF6izX9esL40AQy1P20lU8hq_2jfsHTRsm4eLBMt-ORtsJ9SO6OpaIPtXfH5eMcUTeQbw4kgaFa3rwWz0XQhMIdnVnIC7AfEpnHHdC59BMUjRAdi-ev0LuEd_d4sdcQ6L7Iv2WamdzSMa7eiO23rVGQR_lzzX8UmSPjXYY4ffoYRMUJqKVSCghfI3T1DVHLfODyoeCuV2dK5sZXonV1wtxX5Rd0qpB3jER5YKGk6lpF-rA
  LISTS:
  - ls000000000
  - ls111111111
  IGNOREDLISTS:
  - ls222222222
  - ls333333333
  TRACE: false
  HEADLESS: true
  BROWSERPATH:
SYNC:
  MODE: dry-run
  HISTORY: false
  RATINGS: true
  WATCHLIST: true
  LISTS: true
  TIMEOUT: 15m
TRAKT:
  CLIENTID: 0d0ed3e9523debc2ca1e182b2761e68f86c6ecce9d2ae23a12c95e9b438b87ce
  CLIENTSECRET: 0f09177b9bb13d3f705950fa4d2738dc00684348fde3eeaf5deae2c110f5e87c
  EMAIL: user@domain.com
  PASSWORD: password123
